### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by rzvxa** [squeek502/zua#1]
Hello @squeek502,

what is the state of this project? Are you going to keep developing it?
I want to help with the development of this project. Right now I'm working on a programming language and my target runtime is Lua virtual machine so it would be nice to work with somebody reimplementing it in a modern language possibly with the addition of a jit compiler.

I'm confident with C++ and Rust and I've read a good amount of C throughout my life because of third-party libraries but I haven't used Zig outside of Hello World examples, With that said I mostly have no issue understanding the already written Zig code.

So I'm looking forward to hearing back from you, Since it's been 5 years from the day you created this project and 2 years from the last commit I understand that you no longer have any interest in continuing the development of `zua`.

Have a great day!

**Comment by squeek502** [comment]
The state of the project is basically that it's on hold for now. I'd like to work more on it but have been working on other things and am not sure when I'll get back to it.

In terms of the state of the code:
- The lexer and parser are pretty solid I think
- Needs to be updated to work with the latest Zig version
- Last I worked on it, I got a bit stuck when trying to implement the conversion of `if` statements from AST -> bytecode

You're more than welcome to continue working on this however you'd like. I could also work on getting the code updated for latest Zig if that'd be helpful for you.

**Comment by rzvxa** [comment]
I'm grateful that you would offer to do the updating. I don't want to give you any trouble but I won't lie it would be nice if you do so since you have the context and understanding of the code.

I've noticed that you are linking with Lua, Is that just for testing? Have you considered licensing Zua under the same terms as the Lua project? I can imagine porting Lua to Zig to be a much better starting point, especially for keeping a strong backward compatibility.

**Comment by squeek502** [comment]
Sounds good, I'll prioritize getting this updated to work with latest Zig soon. It's been something I've been meaning to do.

---

Yes, Lua is only linked during tests. This allows Zua to use the real Lua code to determine what to expect for test cases, see https://github.com/squeek502/zua/commit/74d3d52ae2308a5e5b90f6d7d2912bb4fd646f72. This means that compiler tests [can look like this](https://github.com/squeek502/zua/blob/dbc804321a9581f3c7c546af44d98507bd671491/src/compiler.zig#L1203-L1208):

```zig
test "gettable" {
    try testCompile("a.b()");
    try testCompile("a.b(c.a)");
    try testCompile("a[true]()");
    try testCompile("a[1]()");
}
```
and each `testCompile` call will (1) run the code through Zua and compile it to bytecode and (2) run the code through PUC Lua and compile it to bytecode and (3) check that they exactly match

The main Zua binary is 100% Zig though, no C involved.

---

The primary (and only) goal of Zua for me was learning, so I didn't want to do a direct port. I have been using other methods to determine/maintain compatibility, like [fuzz testing](https://www.ryanliptak.com/blog/fuzzing-as-test-case-generator/).

I've been using the 0BSD license more than Unlicense lately, so I may switch Zua to that. MIT could work too but I'm somewhat of a fan of maximally permissive licenses.

**Comment by rzvxa** [comment]
> Sounds good, I'll prioritize getting this updated to work with latest Zig soon. It's been something I've been meaning to do.
Thanks

> and each testCompile call will (1) run the code through Zua and compile it to bytecode and (2) run the code through PUC Lua and compile it to bytecode and (3) check that they exactly match

Nice, Comparing the stacks is also a good idea when it comes to testing the actual virtual machine.

> The primary (and only) goal of Zua for me was learning, so I didn't want to do a direct port. I have been using other methods to determine/maintain compatibility, like [fuzz testing](https://www.ryanliptak.com/blog/fuzzing-as-test-case-generator/).

My hesitance for a complete rewrite is because of tables, And then I saw your comment in the `table.zig` regarding the difficulties that you've noticed. I guess the array part can be pretty straightforward to match but the hashmap part at the very least needs to use the same hashing function. Do you remember what was your issue with it when working on it?

**Comment by squeek502** [comment]
> My hesitance for a complete rewrite is because of tables, And then I saw your comment in the `table.zig` regarding the difficulties that you've noticed. I guess the array part can be pretty straightforward to match but the hashmap part at the very least needs to use the same hashing function. Do you remember what was your issue with it when working on it?

It's been too long to remember details, but there are some relevant comments in the implementation:

https://github.com/squeek502/zua/blob/dbc804321a9581f3c7c546af44d98507bd671491/src/table.zig#L203-L217

I remember the Zua table implementation being fairly incomplete. However, I'm not actually sure the hashing function needs to match exactly, since Lua tables don't guarantee a consistent iteration order when using `next`/`pairs`. I could be missing something about the importance of the hashing function, though.

**Comment by rzvxa** [comment]
I can see you already figured out the length for arrays with holes in them. Maybe the same hashing function isn't necessary since it isn't mentioned in the language spec but LuaJIT also uses the majority of the original table source code so it makes me think that there are more compatibility concerns when it comes to tables.
It uses a [minimal](https://github.com/LuaJIT/LuaJIT/blob/0d313b243194a0b8d2399d8b549ca5a0ff234db5/src/host/minilua.c#L1347) version of lua which brings most things including the underlying table implementation.

**Comment by squeek502** [comment]
I believe minilua is only used during the LuaJIT build process (to execute things like [genversion.lua](https://github.com/LuaJIT/LuaJIT/blob/0d313b243194a0b8d2399d8b549ca5a0ff234db5/src/host/genversion.lua), [dynasm.lua](https://github.com/LuaJIT/LuaJIT/blob/0d313b243194a0b8d2399d8b549ca5a0ff234db5/dynasm/dynasm.lua), etc). Its table implementation is [here](https://github.com/LuaJIT/LuaJIT/blob/0d313b243194a0b8d2399d8b549ca5a0ff234db5/src/lj_tab.c).

**Comment by rzvxa** [comment]
You are right, the actual table implementation is different, however, if I'm not mistaken some internal functions are being used from minilua, for example, the [hash functions](https://github.com/LuaJIT/LuaJIT/blob/0d313b243194a0b8d2399d8b549ca5a0ff234db5/src/lj_tab.c#L26).
I haven't compared them thoroughly but I suspect they share most of the algorithms with some changes to how the logic applies to the runtime.

#### Lua 5.1
```c

/*
** returns the `main' position of an element in a table (that is, the index
** of its hash value)
*/
static Node *mainposition (const Table *t, const TValue *key) {
  switch (ttype(key)) {
    case LUA_TNUMBER:
      return hashnum(t, nvalue(key));
    case LUA_TSTRING:
      return hashstr(t, rawtsvalue(key));
    case LUA_TBOOLEAN:
      return hashboolean(t, bvalue(key));
    case LUA_TLIGHTUSERDATA:
      return hashpointer(t, pvalue(key));
    default:
      return hashpointer(t, gcvalue(key));
  }
}
```

#### LuaJIT
```c
/* Hash an arbitrary key and return its anchor position in the hash table. */
static Node *hashkey(const GCtab *t, cTValue *key)
{
  lj_assertX(!tvisint(key), "attempt to hash integer");
  if (tvisstr(key))
    return hashstr(t, strV(key));
  else if (tvisnum(key))
    return hashnum(t, key);
  else if (tvisbool(key))
    return hashmask(t, boolV(key));
  else
    return hashgcref(t, key->gcr);
  /* Only hash 32 bits of lightuserdata on a 64 bit CPU. Good enough? */
}
```

While they have an entirely different way of type checking and pointer dereferencing they are still keeping most things short circuit with the minilua.

But I agree that it may not be necessary and it is probably done in this way to prevent redundant work. I just think having the freedom of directly porting some parts to Zig is a nice privilege to have.

**Comment by squeek502** [comment]
It's not important, but I really don't think minilua is involved. LuaJIT's `hashstr` is [here](https://github.com/LuaJIT/LuaJIT/blob/0d313b243194a0b8d2399d8b549ca5a0ff234db5/src/lj_tab.h#L42), for example. And `hashnum` is definitely different between [LuaJIT](https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_tab.h#L45) and [PUC Lua](https://www.lua.org/source/5.1/ltable.c.html).

**Comment by rzvxa** [comment]
Oh, you are absolutely right, I didn't notice that it was redefined there. I was wrong and now that I think of it, It makes sense, since the type-checking is happening using the far left bit of the ptr so we need to omit it to get the value of the ptr as a number(well that's my guess since I've seen this being used to unify pointers and number types). I also guess there is a 2-bit flag for the tri-color GC markings.

Anyway, Sorry to bother you with this discussion.

**Comment by squeek502** [comment]
- Updated for latest master version of Zig: https://github.com/squeek502/zua/commit/fd8fca1c10c2de5e2b7fda52913ac92282ed795a (will likely stick to 0.12.0 proper once it's released)
- Swapped license from Unlicense to 0BSD: https://github.com/squeek502/zua/commit/25b7e2a195159f23832149ec0b16a8de25fb6adc
- Added basic CI: https://github.com/squeek502/zua/commit/9bc89d7914f88123cfdefb0dfa98a9440daa0087

**Comment by rzvxa** [comment]
Well, that was fast. Thanks!
